---
- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- link:
    ~/.dotfiles: ""
    ~/.gitignore:
    ~/.gitconfig:
    ~/.git:
    ~/.shell:
    ~/.vim:
      force: true
    ~/.vimrc:
    ~/.rdbgrc.rb:
    ~/.pryrc:
    ~/.zshrc:
      force: true
    ~/.zshenv:
    ~/.zsh:
    ~/.tmux.conf:
    ~/.tmuxline:
    ~/.rake: rake_global
    ~/.ctags.d/default.ctags: "ctags"
    ~/.config/nvim:
      create: true
      path: lazyvim/*
      glob: true
    ~/.config/nvim/coc-settings.json: "coc-settings.json"
    ~/.config/solargraph/config.yml: "solargraph.yml"
    ~/.rgignore:
    "~/Library/Application Support/espanso":
      create: true
      glob: true
      path: espanso/*
      force: true
