---
- defaults:
- shell:
    - [zsh -i -c -- '@zinit-scheduler burst']
    - [source $HOME/.zshrc, Reloading zsh]
    - [pip3 install --user neovim]
    - [git clone https://github.com/junegunn/vim-plug.git "$HOME/vim-plug"]
    - [mkdir -p $HOME/.local/share/nvim/site/autoload]
    - [cp ~/vim-plug/plug.vim $HOME/.local/share/nvim/site/autoload]
    - [nvim --headless -c "PlugInstall" +qall, Loading nvim plugins]
    - [nvim --headless -c 'CocInstall -sync coc-solargraph coc-json coc-rls coc-tsserver coc-yaml coc-highlight coc-lists coc-eslint|q' +qall, Loading Coc.vim Plugins]
