#!/usr/bin/ruby

def install_or_update(gem_exec,gem)
    if is_installed(gem_exec,gem)
        p "Updating #{gem} using: `#{gem_exec} update -f #{gem}`"
        `#{gem_exec} update -f #{gem}`
    else
         p "Installing #{gem} using: `#{gem_exec} install -f #{gem}`"
        `#{gem_exec} install -f #{gem}`
    end
end

def is_installed(gem_exec, gem)
    gem_installed = `#{gem_exec} list -i '^#{gem}$'`.strip
    return true if gem_installed == 'true'
    false
end

gems = %w(
    solargraph
    rubocop
    reek
)

rubies_dir = '/opt/rubies'
gem_executables = Dir.entries(rubies_dir)
    .reject{ |d| d == '.' || d == '..' }
    .map{ |d| File.join(rubies_dir, d, 'bin', 'gem') }

gem_executables << '/usr/bin/gem'

gem_executables.each do |gem_exec|
    gems.each do |gem|
        install_or_update(gem_exec, gem)
    end
end
