#!/bin/bash

# Setup Brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap caskroom/cask

brew update

# Install softwares
brew install coreutils
brew install jq # cmd line json parser
brew install go

## Install ZSH && Oh-My-Zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

## Other Installs
brew cask install sequel-pro
brew cask install visual-studio-code
brew install httpie
brew install fzf
$(brew --prefix)/opt/fzf/install
brew install ripgrep

## Install Python and Python Libs
brew install python

pip3 install -U spacy
sudo python3 -m spacy download en
sudo python3 -m spacy download en_core_web_lg
pip3 install pandas
